### ISSUE TITLE
implement ui for comments section in a post

### ISSUE THREAD

**Issue by RheaAdh** [RheaAdh/Alumni-Portal#24]

**Comment by mohitshende** [comment]
I want to work on this issue. Could you please assign me this issue?

**Comment by mohitshende** [comment]
There seems to be an issue with email verification. I am not receiving verification emails and that's why I am unable to log in. Without logging in, I don't see a way to see my changes in the browser.

**Comment by RheaAdh** [comment]
check it out now u should be able to login
I'll fix the bug in the mean time thanks for letting me know!

**Comment by mohitshende** [comment]
I was just adding styles and making UI changes but suddenly the code started breaking. It was working fine earlier. I didn't make changes to the logic.
![Screenshot (10)](https://user-images.githubusercontent.com/54403334/135745240-9701b874-b9cd-45e8-94d4-609dc00aa4ed.png)
g.

**Comment by RheaAdh** [comment]
Pull the new code once

**Comment by mohitshende** [comment]
My branch is even with yours.

**Comment by RheaAdh** [comment]
try commenting line 155 on post.js in client
the one which has {console.log(owner.profileImage)}

**Comment by mohitshende** [comment]
> try commenting line 157 in image which is in post.js in client the one which has {console.log(owner.profileImage)}

Actually, it's working fine now without any modification.
